name: Deploy React CV to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: Compress Build Files
        run: |
          cd dist
          zip -r ../upload.zip .

      - name: Upload to AWS Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "upload.zip"
          target: "~"

      - name: Extract on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/azhar.softglaze.com/public_html/*
            sudo unzip -o ~/upload.zip -d /home/azhar.softglaze.com/public_html/
            sudo chown -R nobody:nobody /home/azhar.softglaze.com/public_html/
            rm ~/upload.zip
